#
# Software Name : 5G-all-in-one-helm
# SPDX-FileCopyrightText: Copyright (c) 2022
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.n3iwf }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.global.n3iwf.service.nwu.name }}
  labels:
    project: free5gc-project
    nf: {{ .name }}
spec:
  type: {{ $.Values.global.n3iwf.service.nwu.type }}
  ports:
    - name: nwu
      port: {{ $.Values.global.n3iwf.service.nwu.port }}
      targetPort: {{ $.Values.global.n3iwf.service.nwu.targetport }}
      nodePort: {{ $.Values.global.n3iwf.service.nwu.nodePort }}
      protocol: {{ $.Values.global.n3iwf.service.nwu.protocol }}  
  selector:
    project: free5gc-project
    nf: {{ .name }}
{{- end }}