#
# Software Name : 5G-all-in-one-helm
# SPDX-FileCopyrightText: Copyright (c) 2022
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if eq .Values.global.userPlaneArchitecture "single" }}
{{- with .Values.upf }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "free5gc-upf.fullname" $ }}-{{ .name }}
  labels:
    {{- include "free5gc-upf.labels" $ | nindent 4 }}
    project: free5gc-project
    nf: {{ .name }}
spec:
  serviceName: {{ $.Values.global.upf.service.n4.name }}
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "free5gc-upf.selectorLabels" $ | nindent 6 }}
      project: free5gc-project
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        {{- include "free5gc-upf.upfAnnotations" $ | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/upf/upf-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "free5gc-upf.selectorLabels" $ | nindent 8 }}
        project: free5gc-project
        nf: {{ .name }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .name }}
        image: {{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ .image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        ports:
        - name: n4
          containerPort: 8805
          protocol: UDP
        command: ["{{ .volume.mount }}/wrapper.sh"]
        volumeMounts:
        - mountPath: {{ .volume.mount }}
          name: {{ .volume.name }}
        resources:
            {{- toYaml .resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- if $.Values.global.upf.nodeSelector }}
      nodeSelector: {{- $.Values.global.upf.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ .volume.name }}
        projected:
          sources:
          - configMap:
              name: {{ .configmap.name }}
              items:
              - key: upfcfg.yaml
                path: upfcfg.yaml
              - key: wrapper.sh
                path: wrapper.sh
                mode: 0777
{{- end }}
{{- end }}