name: Install dependencies

on:
  workflow_call:  # This makes the workflow reusable
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"  
  workflow_dispatch:  # Allow manual triggers

permissions:
  contents: read

jobs:
  test-app:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies with Poetry
        working-directory: ./nasp
        run: |
          pip install poetry
          poetry install --no-root
